### PR TITLE
feat(skate-style): Label neighborhoods

### PR DESCRIPTION
**Pull request by KaylaBrady**
ticket: https://app.asana.com/0/1200180014510248/1203180633835794/f
Note: see comment [here](https://app.asana.com/0/0/1203180633835794/1203493380281567/f) for outcome of discussion with design

image

### CODE REVIEW

**Comment by firestack** [comment]
Hmm, is it acceptable to allow [`West Somerville`](https://www.openstreetmap.org/node/158855218) override [`Davis Square`](https://www.openstreetmap.org/node/2448023618)?

I'm not sure what we could do though, maybe we can get Mapnik to render `West Somerville` under it?

I guess I really just want to call attention to the broader question of label conflicts and how do we solve them.
Would we need to keep track of our own exclusions/exceptions/quirks list?

**Review by firestack — APPROVED** [review]
A small note that is probably more for design but the code changes LGTM 👍🏻

**Comment by KaylaBrady** [comment]
Thanks @firestack!

> Hmm, is it acceptable to allow [`West Somerville`](https://www.openstreetmap.org/node/158855218) override [`Davis Square`](https://www.openstreetmap.org/node/2448023618)?
> 
> I'm not sure what we could do though, maybe we can get Mapnik to render `West Somerville` under it?
> 
> I guess I really just want to call attention to the broader question of label conflicts and how do we solve them. Would we need to keep track of our own exclusions/exceptions/quirks list?

This particular case was discussed with design, and the decision was ultimately to leave "West Somerville" as-is for now until we get user feedback about specific areas they would want identified differently. If we go down that route I think we likely would have to track a quirks list as you suggested - either in the style files, or by directly manipulating the priority order of places [set in the DB](https://github.com/mbta/tile-server/blob/3be6a046af2aebf8dd3b95fd49b1e77f769e376a/etc/osm-smartrak.osm2pgsql.mml#L438)).

There are also ways we could generally change how overlaps are avoided (like with [`text-placement-type`](https://cartocss.readthedocs.io/en/latest/mapnik_api.html#text-placement-type)), but that could also result in more clutter.

**Review by lemald — APPROVED** [review]

**Comment by firestack** [comment]
Awesome, Thank you for the detailed response @KaylaBrady! 🙏🏻
Feeling better about how we can resolve issues if it comes up.

**Comment by lemald** [comment]
"Davis Square" is probably preferable overall, especially for users thinking in the context of MBTA stations, but "West Somerville" is also pretty widely-recognized so I think it's all right.

**Pull request merged**
