### PR TITLE
New map style

### PR DESCRIPTION
**Pull request by lboyarsky**
Ticket: [Find the way to tweak colors, which are too bright, on the map](https://app.asana.com/0/810933294009540/1120065282149158)

image

New style has been approved by the website team and I've launched new tile generation job for production.

### CODE REVIEW

**Comment by gshkolnik** [comment]
not required, but a nice touch would be to include some screenshots.

**Comment by lboyarsky** [comment]
@gshkolnik sure, added

**Review by paulswartz — APPROVED** [review]
:cake:

Can you please put in a ticket for the "different colors, same size, doesn't upload" issue?

**Comment by lboyarsky** [comment]
Done - https://app.asana.com/0/695227265423458/1120172624141170

**Pull request merged**
