### PR TITLE
Support tile copy operation in container

### PR DESCRIPTION
**Pull request by ianwestcott**
https://app.asana.com/0/1113545750913664/1127168947428601

- Add a `copy` mode to the entrypoint script which runs `aws s3 sync` and then exits, bypassing all other functionality (including map data load)
- Configure the AWS CLI to raise the maximum number of concurrent requests from 10 to 100
- Remove trailing whitespace (my editor does this automatically, sorry for diffspam)

## Notes

In testing, the copy time was ~8 hours for ~3.78 million tiles. We could potentially reduce copy time by setting `max_concurrent_requests` to a higher value, as well as setting `max_queue_size` higher than the default of 1000. ([doc ref](https://docs.aws.amazon.com/cli/latest/topic/s3-config.html)) I'm not sure what the optimal values would be for the environment where the copy operation will run (i.e. inside a container on an m5d.large instance in AWS), nor am I sure whether it's worth taking the time to optimize, but I welcome ideas for how to test potential optimizations efficiently.

### CODE REVIEW

**Comment by ianwestcott** [comment]
Whoops, need to update documentation. Stand by.

**Comment by ianwestcott** [comment]
Documentation added.

**Review by lboyarsky — APPROVED** [review]
LGTM

**Comment by ianwestcott** [comment]
Updating container image and Batch job settings.

**Pull request merged**
