### PR TITLE
fix: fully tag Docker image so that push works

### PR DESCRIPTION
**Pull request by lemald**
Super quick fix, but `build_push.sh` wasn't working at first because it wasn't adding the corresponding tags for the remote repository, causing the push to not do anything (other than try to push the old version that was tagged properly).

### CODE REVIEW

**Review by paulswartz — APPROVED** [review]
:cake:

A future change might be to use the `mbta/actions` for this?

**Comment by lemald** [comment]
> 🍰
> 
> A future change might be to use the `mbta/actions` for this?

I feel like I recall @ianwestcott saying there was some reason we hadn't done this in the past (perhaps because of the significance of how the `latest` tag is used in relation to the batch job), but it looks like you can specify a `docker-additional-tags` input to the action, so maybe that isn't an issue.

**Comment by ianwestcott** [comment]
There wasn't a great reason, tbh; it was in the days before GitHub Actions, and it was deemed too much effort to automate a build process that wasn't going to see a lot of additional development at the time. But now that that's changing I think it's a worthwhile improvement! Also you're correct that `docker-additional-tags` exists to solve this problem.

**Comment by lemald** [comment]
Okay, thanks! For now I'm going to merge this to fix the script as it is, but I've also created a [followup ticket to move to GitHub Actions for building](https://app.asana.com/0/1152340551558956/1203226915189268/f).

**Pull request merged**
